[package]
name = "anns-war"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fvecs_readers = "0.1.0"
memory-stats = "1.1.0"
